/* Warning: This file is generated by ./collate-test - do not modify directly! */
extern bool test_stem1();
extern bool test_stem2();
extern bool test_stem3();
extern bool test_stemempty1();
extern bool test_stemlangs2();
