/* Warning: This file is generated by ./collate-test - do not modify directly! */
extern bool test_snippet1();
extern bool test_snippetstem1();
extern bool test_snippetphrase1();
extern bool test_snippetmisc1();
extern bool test_snippet_termcover1();
extern bool test_snippet_termcover2();
extern bool test_snippet_empty();
extern bool test_snippet_start_nonspace();
