/* Warning: This file is generated by ./collate-test - do not modify directly! */
extern bool test_termgen1();
extern bool test_tg_spell1();
extern bool test_tg_spell2();
extern bool test_tg_max_word_length1();
