/* Warning: This file is generated by ./collate-test - do not modify directly! */
extern bool test_matchspy1();
extern bool test_matchspy2();
extern bool test_matchspy4();
extern bool test_matchspy5();
extern bool test_matchspy6();
