/* Warning: This file is generated by ./collate-test - do not modify directly! */
extern bool test_synonym1();
extern bool test_synonym2();
extern bool test_synonym3();
extern bool test_synonym4();
extern bool test_opmax1();
