/* Warning: This file is generated by ./collate-test - do not modify directly! */
extern bool test_latlongpostingsource1();
extern bool test_latlongcoords1();
extern bool test_latlongmetric1();
extern bool test_latlongmetric2();
extern bool test_latlongkeymaker1();
