/* Warning: This file is generated by ./collate-test - do not modify directly! */
extern bool test_valuerange1();
extern bool test_valuerange2();
extern bool test_valuerange5();
extern bool test_valuerange6();
extern bool test_valuerange7();
extern bool test_valuege1();
extern bool test_valuege2();
extern bool test_valuele1();
extern bool test_valuege3();
extern bool test_valuege4();
extern bool test_valuerange3();
extern bool test_valuerange4();
extern bool test_valuerangematchesub1();
