/* Warning: This file is generated by ./collate-test - do not modify directly! */
extern bool test_consistency3();
extern bool test_pctcutoff4();
extern bool test_pctcutoff5();
extern bool test_topercent3();
extern bool test_topercent4();
extern bool test_topercent5();
extern bool test_topercent6();
extern bool test_topercent7();
extern bool test_checkzeromaxpartopt1();
