/* Warning: This file is generated by ./collate-test - do not modify directly! */
extern bool test_badtransaction1();
extern bool test_committransaction1();
extern bool test_canceltransaction1();
extern bool test_canceltransaction2();
extern bool test_canceltransaction3();
