/* Warning: This file is generated by ./collate-test - do not modify directly! */
extern bool test_compactoldnorenumber1();
extern bool test_compactoldmerge1();
extern bool test_compactoldmultichunks1();
extern bool test_compactoldstub1();
extern bool test_compactoldstub2();
extern bool test_compactoldstub3();
extern bool test_compactoldstub4();
extern bool test_compactoldmissingtables1();
extern bool test_compactoldmergesynonym1();
extern bool test_compactoldempty1();
extern bool test_compactoldmultipass1();
